# source for this config is
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
#
language: ruby
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler # caching bundler gem packages will speed up build

rvm:
  - 2.6.0


before_script:
  - chmod +x ./build-tools/ci-build.sh # or do this locally and commit
script:
  - ./build-tools/ci-build.sh


##################################
  # language: node_js
# node_js:
#   - 10.15.0
# cache: npm
# install:
#   - npm ci
# before_script:
#   # running code climate
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
# script:
#   - npm test
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# https://docs.travis-ci.com/user/deployment/pages/#further-configuration
# how to config this
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
