language: node_js
node_js:
  - 10.15.0
cache: npm
install:
  - npm ci
# before_script:
#   # running code climate
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
script:
  - npm test
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# https://docs.travis-ci.com/user/deployment/pages/#further-configuration
# how to config this
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
